export const SITES = [
  {
    id: 0,
    siteName: "Chicago Architecture Center",
    type: "Educational",
    address: "111 E Wacker Dr",
    city: "Chicago",
    state: "IL",
    zip: "60601",
    siteContact: "John Smith",
    siteStatus: "Active",
  },
  {
    id: 1,
    siteName: "Willis Tower",
    type: "Business",
    address: "233 S Wacker Dr",
    city: "Chicago",
    state: "IL",
    zip: "60606",
    siteContact: "Mary Mack",
    siteStatus: "Active",
  },
  {
    id: 2,
    siteName: "The Rookery Building",
    type: "Institutional",
    address: "209 S LaSalle St",
    city: "Chicago",
    state: "IL",
    zip: "60604",
    siteContact: "Don Campbell",
    siteStatus: "Inactive",
  },
  {
    id: 3,
    siteName: "Park Place Tower",
    type: "Residential",
    address: "655 W Irving Park Rd",
    city: "Chicago",
    state: "IL",
    zip: "60613",
    siteContact: "Franklin James",
    siteStatus: "Inactive",
  },
  {
    id: 4,
    siteName: "Malcolm X College",
    type: "Educational",
    address: "1900 W. Jackson",
    city: "Chicago",
    state: "IL",
    zip: "60612",
    siteContact: "Martin King",
    siteStatus: "Active",
  },
];
